### PR TITLE
Support providing a localPort parameter to the connect method.

### PR DESCRIPTION
**Pull request by carlossilva**
Provides code for implementing https://github.com/cronn-de/ssh-proxy/issues/2

### CODE REVIEW

**Comment by carlossilva** [comment]
Seems like your build failed since your last commit and hence the reason this build also failed. Hopefully you incorporate this feature.

**Comment by carlossilva** [comment]
I have added the assert and tests. Build passed, would be nice if you could push a new release to the maven repos.

Thanks.

**Comment by bwaldvogel** [comment]
Available in version 1.1. It’s available via jcenter.

**Comment by carlossilva** [comment]
Great, thanks a lot!

**Pull request merged**
